// <auto-generated />
using Configurator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Configurator.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230925000006_AddConstraints")]
    partial class AddConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Configurator.Data.Models.Package", b =>
                {
                    b.Property<int>("PackageGroupId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("PackageGroupId", "TableName");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            PackageGroupId = 3,
                            TableName = "TRAD_Aluno",
                            Id = 1
                        },
                        new
                        {
                            PackageGroupId = 3,
                            TableName = "TRAD_Escola",
                            Id = 2
                        },
                        new
                        {
                            PackageGroupId = 3,
                            TableName = "TRAD_Professor",
                            Id = 3
                        });
                });

            modelBuilder.Entity("Configurator.Data.Models.PackageGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PackageGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PackageGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PackageGroupName = "Folha"
                        },
                        new
                        {
                            Id = 2,
                            PackageGroupName = "Contábil"
                        },
                        new
                        {
                            Id = 3,
                            PackageGroupName = "Traduções"
                        });
                });

            modelBuilder.Entity("Configurator.Data.Models.Package", b =>
                {
                    b.HasOne("Configurator.Data.Models.PackageGroup", "PackageGroups")
                        .WithMany("Packages")
                        .HasForeignKey("PackageGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageGroups");
                });

            modelBuilder.Entity("Configurator.Data.Models.PackageGroup", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
